export const JWT_GUARD_METADATA_KEY = 'JWT_GUARD_METADATA_KEY';
export const API_VERSION_GUARD_METADATA_KEY = 'API_VERSION_GUARD_METADATA_KEY';
export const USER_PERMISSION_GUARD_METADATA_KEY = Symbol('USER_PERMISSION_GUARD_METADATA_KEY');
